In [5]:
import numpy as np
import time
from scipy.linalg import solve
from scipy.sparse.linalg import dsolve
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, lil_matrix

In [6]:
def nam_val(var):
    for (s, v) in globals().items():
        if id(v)==id(var):
            print(s,'=' )
            print(var)
            
def nam_vals(vars):
    for var in vars:
        for (s, v) in globals().items():
            if id(v)==id(var):
                print(s,'=' )
                print(v)

In [7]:
##definition of matrix
list1=[[0,1,2],[3,4,5]]
mat1=np.array(list1)
nam_vals([list1,mat1])

list1 =
[[0, 1, 2], [3, 4, 5]]
mat1 =
[[0 1 2]
 [3 4 5]]


In [11]:
##Operagion of matrix
mat1=np.array([[1,2,3],[4,5,6]])
mat2=np.array([[1,1,1],[1,1,1]])
mat1T=mat1.T
mat2T=mat2.T
nam_vals([mat1,mat1T,mat2,mat2T])
matZero=np.zeros((2,3))
matOne=np.ones((2,3))
nam_vals([matZero,matOne])
print("mat1*mat2 =")
print(mat1*mat2)
print("dot(mat1T,mat2)")
print(np.dot(mat1T,mat2))
print("dot(mat1,mat2T)")
print(np.dot(mat1,mat2T))
mat3=np.array([[1,2],[4,5]])
mat3I=np.linalg.inv(mat3)
nam_vals([mat3,mat3I])
for c in mat2:
    print(c)

mat1 =
[[1 2 3]
 [4 5 6]]
mat1T =
[[1 4]
 [2 5]
 [3 6]]
mat2 =
[[1 1 1]
 [1 1 1]]
mat2T =
[[1 1]
 [1 1]
 [1 1]]
matZero =
[[0. 0. 0.]
 [0. 0. 0.]]
matOne =
[[1. 1. 1.]
 [1. 1. 1.]]
mat1*mat2 =
[[1 2 3]
 [4 5 6]]
dot(mat1T,mat2)
[[5 5 5]
 [7 7 7]
 [9 9 9]]
dot(mat1,mat2T)
[[ 6  6]
 [15 15]]
mat3 =
[[1 2]
 [4 5]]
mat3I =
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[1 1 1]
[1 1 1]


3

In [9]:
# Solve Ax=b
# Definition A, b
L=1000
A=np.zeros((L,L))
for i in range(0,A.shape[0]):
    for j in range(0,A.shape[1]):
        if(i==j):
            A[i][j]=1.
        elif(np.abs(i-j)==1):
            A[i][j]=-0.5
b=np.ones((L,1))
x=np.zeros((L,1))
nam_vals([A,b,x])

A =
[[ 1.  -0.5  0.  ...  0.   0.   0. ]
 [-0.5  1.  -0.5 ...  0.   0.   0. ]
 [ 0.  -0.5  1.  ...  0.   0.   0. ]
 ...
 [ 0.   0.   0.  ...  1.  -0.5  0. ]
 [ 0.   0.   0.  ... -0.5  1.  -0.5]
 [ 0.   0.   0.  ...  0.  -0.5  1. ]]
b =
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [

In [10]:
# Solve Ax=b
# Calculation invers matrix
x=np.zeros((L,1))
x=np.dot(np.linalg.inv(A),b)
nam_val(x)
print(np.dot(A,x))

x =
[[  1000.        ]
 [  1998.        ]
 [  2994.        ]
 [  3988.        ]
 [  4980.        ]
 [  5970.        ]
 [  6958.        ]
 [  7944.        ]
 [  8928.        ]
 [  9910.        ]
 [ 10890.        ]
 [ 11868.        ]
 [ 12844.        ]
 [ 13818.        ]
 [ 14790.        ]
 [ 15760.        ]
 [ 16728.        ]
 [ 17694.        ]
 [ 18658.        ]
 [ 19620.        ]
 [ 20580.        ]
 [ 21538.        ]
 [ 22494.        ]
 [ 23448.        ]
 [ 24400.        ]
 [ 25350.        ]
 [ 26298.        ]
 [ 27244.        ]
 [ 28188.        ]
 [ 29130.        ]
 [ 30070.        ]
 [ 31008.        ]
 [ 31944.        ]
 [ 32878.        ]
 [ 33810.        ]
 [ 34740.        ]
 [ 35668.        ]
 [ 36594.        ]
 [ 37518.        ]
 [ 38440.        ]
 [ 39360.        ]
 [ 40278.        ]
 [ 41194.        ]
 [ 42107.99999999]
 [ 43019.99999999]
 [ 43929.99999999]
 [ 44837.99999999]
 [ 45743.99999999]
 [ 46647.99999999]
 [ 47549.99999999]
 [ 48449.99999999]
 [ 49347.99999999]
 [ 50243

In [313]:
# Solve Ax=b
# Iterative method
x=np.zeros((L,1))
error=1
counter=0
while (error>1e-9 and counter<1000):
    counter+=1
    error=0
    sum=0
    for (xi,i) in zip(x,range(0,len(x))):
        old=xi
        a=A[i,0:len(x)]
        u=a[i]*xi+b[i]
        for j in range(0,len(x)):
            u-=a[j]*x[j]
        xi[:]=u/a[i]
    db=np.dot(A,x)-b
    error=np.sqrt(((db*db).sum())/((b*b).sum()))
    print("iteration=",counter,"residual=",error)    
nam_val(x)

iteration= 1 residual= 0.990370301116372
iteration= 2 residual= 0.9834186639059269
iteration= 3 residual= 0.9780990535153659
iteration= 4 residual= 0.9736244614097216
iteration= 5 residual= 0.9696797916314147
iteration= 6 residual= 0.9661079148478013
iteration= 7 residual= 0.9628170041094358
iteration= 8 residual= 0.9597477145197295
iteration= 9 residual= 0.9568590191487519
iteration= 10 residual= 0.9541211442993617
iteration= 11 residual= 0.9515116708479299
iteration= 12 residual= 0.9490132187349481
iteration= 13 residual= 0.9466119922627135
iteration= 14 residual= 0.944296824429681
iteration= 15 residual= 0.9420585257265993
iteration= 16 residual= 0.9398894266283627
iteration= 17 residual= 0.9377830477148501
iteration= 18 residual= 0.9357338564410885
iteration= 19 residual= 0.9337370842734498
iteration= 20 residual= 0.9317885868394395
iteration= 21 residual= 0.9298847353411052
iteration= 22 residual= 0.9280223310958746
iteration= 23 residual= 0.9261985374578237
iteration= 24 residual

iteration= 191 residual= 0.7545488862407853
iteration= 192 residual= 0.7537859325368242
iteration= 193 residual= 0.7530242676782876
iteration= 194 residual= 0.7522638813967643
iteration= 195 residual= 0.751504763584949
iteration= 196 residual= 0.750746904293777
iteration= 197 residual= 0.7499902937296186
iteration= 198 residual= 0.7492349222515299
iteration= 199 residual= 0.7484807803685625
iteration= 200 residual= 0.7477278587371246
iteration= 201 residual= 0.7469761481583971
iteration= 202 residual= 0.7462256395758027
iteration= 203 residual= 0.7454763240725225
iteration= 204 residual= 0.7447281928690649
iteration= 205 residual= 0.7439812373208812
iteration= 206 residual= 0.7432354489160282
iteration= 207 residual= 0.7424908192728771
iteration= 208 residual= 0.7417473401378656
iteration= 209 residual= 0.7410050033832959
iteration= 210 residual= 0.740263801005173
iteration= 211 residual= 0.739523725121086
iteration= 212 residual= 0.738784767968129
iteration= 213 residual= 0.7380469219

iteration= 387 residual= 0.6225711658907029
iteration= 388 residual= 0.6219682951496451
iteration= 389 residual= 0.6213660288274906
iteration= 390 residual= 0.6207643659737443
iteration= 391 residual= 0.6201633056447368
iteration= 392 residual= 0.6195628469035218
iteration= 393 residual= 0.6189629888197753
iteration= 394 residual= 0.6183637304696976
iteration= 395 residual= 0.6177650709359188
iteration= 396 residual= 0.6171670093073995
iteration= 397 residual= 0.6165695446793408
iteration= 398 residual= 0.6159726761530887
iteration= 399 residual= 0.6153764028360472
iteration= 400 residual= 0.614780723841586
iteration= 401 residual= 0.6141856382889537
iteration= 402 residual= 0.6135911453031916
iteration= 403 residual= 0.6129972440150478
iteration= 404 residual= 0.612403933560895
iteration= 405 residual= 0.6118112130826464
iteration= 406 residual= 0.6112190817276767
iteration= 407 residual= 0.6106275386487401
iteration= 408 residual= 0.610036583003893
iteration= 409 residual= 0.60944621

iteration= 601 residual= 0.5061534407260915
iteration= 602 residual= 0.5056642542460134
iteration= 603 residual= 0.5051755404455194
iteration= 604 residual= 0.5046872988580674
iteration= 605 residual= 0.5041995290177572
iteration= 606 residual= 0.5037122304593251
iteration= 607 residual= 0.5032254027181385
iteration= 608 residual= 0.5027390453301898
iteration= 609 residual= 0.5022531578321
iteration= 610 residual= 0.5017677397611098
iteration= 611 residual= 0.501282790655079
iteration= 612 residual= 0.5007983100524819
iteration= 613 residual= 0.5003142974924041
iteration= 614 residual= 0.4998307525145393
iteration= 615 residual= 0.4993476746591862
iteration= 616 residual= 0.4988650634672432
iteration= 617 residual= 0.4983829184802131
iteration= 618 residual= 0.49790123924019064
iteration= 619 residual= 0.4974200252898639
iteration= 620 residual= 0.4969392761725104
iteration= 621 residual= 0.49645899143199634
iteration= 622 residual= 0.49597917061276614
iteration= 623 residual= 0.495499

iteration= 799 residual= 0.4179524211200535
iteration= 800 residual= 0.4175483957070908
iteration= 801 residual= 0.41714476035782555
iteration= 802 residual= 0.4167415146966075
iteration= 803 residual= 0.41633865834815265
iteration= 804 residual= 0.41593619093754525
iteration= 805 residual= 0.4155341120902357
iteration= 806 residual= 0.4151324214320408
iteration= 807 residual= 0.4147311185891452
iteration= 808 residual= 0.4143302031880946
iteration= 809 residual= 0.41392967485580234
iteration= 810 residual= 0.4135295332195465
iteration= 811 residual= 0.41312977790696737
iteration= 812 residual= 0.41273040854607057
iteration= 813 residual= 0.4123314247652232
iteration= 814 residual= 0.41193282619315535
iteration= 815 residual= 0.411534612458959
iteration= 816 residual= 0.41113678319208746
iteration= 817 residual= 0.41073933802235524
iteration= 818 residual= 0.4103422765799387
iteration= 819 residual= 0.40994559849537365
iteration= 820 residual= 0.40954930339955165
iteration= 821 residua

In [374]:
x=np.zeros((L,1))
x=solve(A,b)
print(x)

[[  1000.        ]
 [  1998.        ]
 [  2994.        ]
 [  3988.        ]
 [  4980.        ]
 [  5970.        ]
 [  6958.        ]
 [  7944.        ]
 [  8928.        ]
 [  9910.        ]
 [ 10890.        ]
 [ 11868.        ]
 [ 12844.        ]
 [ 13818.        ]
 [ 14790.        ]
 [ 15760.        ]
 [ 16728.        ]
 [ 17694.        ]
 [ 18658.        ]
 [ 19620.        ]
 [ 20580.        ]
 [ 21538.        ]
 [ 22494.        ]
 [ 23448.        ]
 [ 24400.        ]
 [ 25350.        ]
 [ 26298.        ]
 [ 27244.        ]
 [ 28188.        ]
 [ 29130.        ]
 [ 30070.        ]
 [ 31008.        ]
 [ 31944.        ]
 [ 32878.        ]
 [ 33810.        ]
 [ 34740.        ]
 [ 35668.        ]
 [ 36594.        ]
 [ 37518.        ]
 [ 38440.        ]
 [ 39360.        ]
 [ 40277.99999999]
 [ 41193.99999999]
 [ 42107.99999999]
 [ 43019.99999999]
 [ 43929.99999999]
 [ 44837.99999999]
 [ 45743.99999999]
 [ 46647.99999999]
 [ 47549.99999999]
 [ 48449.99999999]
 [ 49347.99999999]
 [ 50243.999

スパースな行列AでのAx=bをscipyを使って解く

In [375]:
#Use scipy.sparse (Sparse Matrix)
data = []
row = []
col = []
for i in range(0,L):
    for j in range(0,L):
        if(i==j):
            data.append(1)
            row.append(i)
            col.append(j)
        elif(np.abs(i-j)==1):
            data.append(-0.5)
            row.append(i)
            col.append(j)
nam_vals([data,row,col])

data =
[1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1, -0.5, -0.5, 1,

In [376]:
Acsr = csr_matrix((data, (row, col)), shape=(L, L))
#Acsr = csr_matrix(A)
bcsr=csr_matrix(b)
xcsr=dsolve.spsolve(Acsr,bcsr)
nam_val(xcsr)

xcsr =
[  1000.           1998.           2994.           3988.
   4980.           5970.           6958.           7944.
   8928.           9910.          10890.          11868.
  12844.          13818.          14790.          15760.
  16728.          17694.          18658.          19620.
  20580.          21538.          22494.          23448.
  24400.          25350.          26298.          27244.
  28188.          29130.          30070.          31008.
  31944.          32878.          33810.          34740.
  35668.          36594.          37518.          38440.
  39360.          40277.99999999  41193.99999999  42107.99999999
  43019.99999999  43929.99999999  44837.99999999  45743.99999999
  46647.99999999  47549.99999999  48449.99999999  49347.99999999
  50243.99999999  51137.99999999  52029.99999999  52919.99999999
  53807.99999999  54693.99999999  55577.99999999  56459.99999999
  57339.99999999  58217.99999999  59093.99999999  59967.99999999
  60839.99999999  61709.99999999 

In [377]:
def func_solve1(A,b):
    output = solve(A,b)
    return output
def func_solve2(A,b):
    Acsr = csr_matrix(A)
    bcsr = csr_matrix(b)
    output = dsolve.spsolve(Acsr,bcsr)
    return output

In [378]:
st=time.time()
x = func_solve1(A,b)
et=time.time()
print(et-st)
st=time.time()
x = func_solve2(A,b)
et=time.time()
print(et-st)

0.023935317993164062
0.006981372833251953
